/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package nmarket;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.*;

/**
 *
 * @author aditn
 */
public class menu extends javax.swing.JFrame {

    /**
     * Creates new form menu
     */
    private boolean connected = false;

    public menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        login = new javax.swing.JMenuItem();
        saveMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        master = new javax.swing.JMenu();
        products = new javax.swing.JMenuItem();
        category_product = new javax.swing.JMenuItem();
        employee = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        stok = new javax.swing.JMenuItem();
        inventory = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fileMenu.setMnemonic('f');
        fileMenu.setText("File");

        login.setMnemonic('o');
        login.setText("Login");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        fileMenu.add(login);

        saveMenuItem.setMnemonic('s');
        saveMenuItem.setText("Logout");
        saveMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(saveMenuItem);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        master.setMnemonic('e');
        master.setText("Master");

        products.setMnemonic('t');
        products.setText("Products");
        products.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productsActionPerformed(evt);
            }
        });
        master.add(products);

        category_product.setMnemonic('y');
        category_product.setText("Category Product");
        category_product.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                category_productActionPerformed(evt);
            }
        });
        master.add(category_product);

        employee.setMnemonic('p');
        employee.setText("Employee");
        master.add(employee);

        menuBar.add(master);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Transaction");

        contentMenuItem.setMnemonic('c');
        contentMenuItem.setText("Inventory");
        contentMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contentMenuItemActionPerformed(evt);
            }
        });
        helpMenu.add(contentMenuItem);

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("Sale");
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        jMenu1.setText("Report");

        stok.setText("Stock");
        stok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stokActionPerformed(evt);
            }
        });
        jMenu1.add(stok);

        inventory.setText("Inventory");
        jMenu1.add(inventory);

        menuBar.add(jMenu1);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void productsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productsActionPerformed
        // TODO add your handling code here:
        if (connected) {
            products m = new products();
            Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
            m.setAlwaysOnTop(true);
            m.requestFocus();
            m.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(rootPane, "anda belum terknoneksi", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_productsActionPerformed

    private void stokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stokActionPerformed

    private void contentMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contentMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contentMenuItemActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        // TODO add your handling code here:
        connected = true;
        JOptionPane.showMessageDialog(rootPane, "Connected", "Connected", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_loginActionPerformed

    private void saveMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveMenuItemActionPerformed
        // TODO add your handling code here:
        connected = false;
        JOptionPane.showMessageDialog(rootPane, "Disconnected", "Disconnected", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_saveMenuItemActionPerformed

    private void category_productActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_category_productActionPerformed
        // TODO add your handling code here:
        if (connected) {
            category m = new category();
            Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
            m.setAlwaysOnTop(true);
            m.requestFocus();
            m.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(rootPane, "anda belum terknoneksi", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_category_productActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
                Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
//                JOptionPane.showMessageDialog(rootPane,"masuk sini", "Error", JOptionPane.ERROR_MESSAGE);
//                menu().setBounds(0,0,screenSize.width, screenSize.height);

//                products m = new products();
//                m.setAlwaysOnTop(true);
//                m.setBounds(0,0,screenSize.width, screenSize.height);
//                m.toFront();
//                m.requestFocus(); 
//                m.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem category_product;
    private javax.swing.JMenuItem contentMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem employee;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuItem inventory;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem login;
    private javax.swing.JMenu master;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem products;
    private javax.swing.JMenuItem saveMenuItem;
    private javax.swing.JMenuItem stok;
    // End of variables declaration//GEN-END:variables

}
